Train:
  epoches: 
  weights: 
  optim: 
  base_lr:  
  if_train_query_encoder_textFeatureEncoder: 
  inter_pred_th: 
  device_ids: 
  loss_gamma:
    loss_start: 
    loss_end: 
    iou_loss: 
    inter_loss: 
    similarity_loss: 
DataSet:
  Vedio_feature_path: 
  train_ann_data_path: 
  eval_ann_data_path: 
  text_encoder_root: 
  batch_size: 
Model:
  text_feature_dim: 
  video_feature_dim: 
  use_inter_pred: 
Logs_dir: 
save_dir: 
