Train:
  epoches: 
  weights: 
  # weights:
  optim: AdamW # SGD ASGD Rprop Adagrad Adadelta RMSprop Adam Adamax AdamW
  base_lr:  
  if_train_query_encoder_textFeatureEncoder: True
  inter_pred_th: 
  device_ids: [0]
  loss_gamma:
    loss_start: 
    loss_end: 
    iou_loss: 
    inter_loss: 
    similarity_loss: 
DataSet:
  Vedio_feature_path: 
  train_ann_data_path: 
  eval_ann_data_path: 
  text_encoder_root: 
  # text_encoder_root: '/data2/liangxiaoyuan_data/NLP_models/bert-large-uncased'
  batch_size: 
Model:
  text_feature_dim: 
  video_feature_dim: 
  use_inter_pred: 
  # use_inter_pred: False
Logs_dir: 
save_dir: 